"""Add Blog Tables

Revision ID: 31b683b1d3cb
Revises: e5170cc45f3f
Create Date: 2025-10-06 06:09:47.121944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b683b1d3cb'
down_revision: Union[str, None] = 'e5170cc45f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
