"""Enhanced Note Table

Revision ID: 3799390b5baf
Revises: 2195aa4d39aa
Create Date: 2025-10-03 06:36:08.053023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3799390b5baf'
down_revision: Union[str, None] = '2195aa4d39aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhanced_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('notes', 'has_ai_summary')
    op.drop_column('notes', 'has_ai_enhancement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('has_ai_enhancement', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('has_ai_summary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('enhanced_notes')
    # ### end Alembic commands ###
