"""Add task metadata and user profiles

Revision ID: 8a8b69ed0947
Revises: 74bb38e2f7f3
Create Date: 2025-09-29 07:54:05.452349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8b69ed0947'
down_revision: Union[str, None] = '74bb38e2f7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'task_metadata', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_status', 'task_metadata', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_metadata_task_id'), 'task_metadata', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_metadata_user_id'), 'task_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_metadata_user_id'), table_name='task_metadata')
    op.drop_index(op.f('ix_task_metadata_task_id'), table_name='task_metadata')
    op.drop_index('idx_user_status', table_name='task_metadata')
    op.drop_index('idx_user_created', table_name='task_metadata')
    op.drop_table('task_metadata')
    # ### end Alembic commands ###
