"""Add order by Questions, Quiz Table

Revision ID: 952404abe166
Revises: 9b784dbb3ef4
Create Date: 2025-10-04 17:49:14.558856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952404abe166'
down_revision: Union[str, None] = '9b784dbb3ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
