"""Remove order by Note Table

Revision ID: 9b784dbb3ef4
Revises: b96594aaebe3
Create Date: 2025-10-04 17:37:17.722360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b784dbb3ef4'
down_revision: Union[str, None] = 'b96594aaebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
