"""midufy QuizSubmission Table

Revision ID: d95d8c0f093f
Revises: ab53660d87bb
Create Date: 2025-10-04 04:05:39.685987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95d8c0f093f'
down_revision: Union[str, None] = 'ab53660d87bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_submissions_note_id_fkey', 'quiz_submissions', type_='foreignkey')
    op.drop_column('quiz_submissions', 'note_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submissions', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quiz_submissions_note_id_fkey', 'quiz_submissions', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
